#Nugent score with all the variables

mylogit <- glm(formula = Nugent.score.cat ~ Shannon.s.Diversity, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Amsels.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Age.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ BMI.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Ethnicity.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Marital.Status.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Highest.Education.Level.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Current.or.chronic.conditions...y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Infections..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ BV..number.of.episodes.2.months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ BV..number.of.episodes.year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ BV..number.of.episodes.lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Yeast..2months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Yeast..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Yeast..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ UTI..2.months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ UTI..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ UTI..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Trich..2.months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Trich..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Trich..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Warts..2months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Warts..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Warts..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Herpes..2months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Herpes..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genital.Herpes..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Chlamydia..2.months., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Chlamydia..year., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Chlamydia..lifetime., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Gonorrhea, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Syphillis, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Antimicrobial.Use..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ X.Non..Prescription..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Freq.of.Menstrual.Period.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Tampon.Use.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..g., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..term., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..p., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..sa., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..ta., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Pregnancy.History..l., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Use.of.douche.products..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Used.in.the.past.48.hours, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Used.in.past.48.hours, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Sexual.Partners.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Number.partners.in.past.2.months.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Number.partners.in.past.year.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Freq.oral.sex.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Freq.anal.sex.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Freq.sex.toy.use.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ use.of.drugs..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ alcohol.use..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Actinobacteria.sp., data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Atopobium.vaginae, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Clostridia.sp..BVAB2, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Clostridium.genomosp..BVAB3, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Escherichia.coli, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Gardnerella.vaginalis.Group.A, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Gardnerella.vaginalis.Group.B, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Gardnerella.vaginalis.Group.C, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Gardnerella.vaginalis.Group.D, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Klebsiella.pneumoniae, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Lactobacillus.crispatus, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Lactobacillus.gasseri, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Lactobacillus.iners, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Lactobacillus.jensenii, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Megasphaera.sp..genomosp..type.1, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Actinobacteria, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Bacteria, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Bacteroidetes, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Clostridium, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Firmicutes, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Lactobacillus, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Prevotella, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Proteobacteria, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Streptococcus, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Prevotella.amnii, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Streptococcus.devriesei, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Prevotella.timonensis, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Contraception.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Presence.Symptoms.2wks, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Abnormal.discharge.2wks, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Abnormal.odor.2wks, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Irritation.Discomfort.2wks, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Symptoms.2wks, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Presence.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Irritation.Discomfort.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Other.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Preg.livebirth.ever, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Chlamydia.ever, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Bac.STI.ever, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Herpes.ever, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Genwarts.ever, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ any.sx.pain, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ sx.pain.50.over, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ sx.pain.100, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contraception.H, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contraception.S.S, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contraception.S.P, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contraception.B.M, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contraception.C.IUD, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ HContr.Combination.pill, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ HContr.mirena, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ contr_type, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ condoms.48h, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ probiotics.2.months, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ days.since.LMP, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ weeks.since.LMP, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ weeks.since.LMP.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ CST.cat, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Abnormal.odor.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ Abnormal.discharge.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = Nugent.score.cat ~ oral.sex.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))

#CST.cat with all variables
mylogit <- glm(formula = CST.cat ~ Shannon.s.Diversity, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Amsels.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Age.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BMI.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Ethnicity.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Marital.Status.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Highest.Education.Level.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Current.or.chronic.conditions...y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Infections..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gonorrhea, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Syphillis, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Antimicrobial.Use..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ X.Non..Prescription..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.of.Menstrual.Period.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Tampon.Use.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..g., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..term., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..p., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..sa., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..ta., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..l., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Use.of.douche.products..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Used.in.the.past.48.hours, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Used.in.past.48.hours, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Sexual.Partners.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Number.partners.in.past.2.months.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Number.partners.in.past.year.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.oral.sex.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.anal.sex.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.sex.toy.use.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ use.of.drugs..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ alcohol.use..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Actinobacteria.sp., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Atopobium.vaginae, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Clostridia.sp..BVAB2, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Clostridium.genomosp..BVAB3, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Escherichia.coli, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.A, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.B, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.C, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.D, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Klebsiella.pneumoniae, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.crispatus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.gasseri, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.iners, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.jensenii, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Megasphaera.sp..genomosp..type.1, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Actinobacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Bacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Bacteroidetes, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Clostridium, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Firmicutes, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Lactobacillus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Prevotella, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Proteobacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Streptococcus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Prevotella.amnii, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Streptococcus.devriesei, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Contraception.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Presence.Symptoms.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.discharge.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.odor.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Irritation.Discomfort.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Symptoms.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Presence.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Irritation.Discomfort.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Preg.livebirth.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Bac.STI.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Herpes.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genwarts.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ any.sx.pain, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ sx.pain.50.over, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ sx.pain.100, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.H, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.S.S, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.S.P, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.B.M, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.C.IUD, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ HContr.Combination.pill, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ HContr.mirena, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contr_type, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ condoms.48h, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ probiotics.2.months, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ days.since.LMP, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ weeks.since.LMP, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ weeks.since.LMP.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Nugent.score.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)

mylogit <- glm(formula = CST.cat ~ Prevotella.timonensis, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = CST.cat ~ Abnormal.discharge.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = CST.cat ~ Abnormal.odor.48hrs, data=total, family = binomial(link = "logit"))
mylogit <- glm(formula = CST.cat ~ oral.sex.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))
