#Nugent score with all the variables (uni ordinal log reg)
m <- polr(Nugent.score.cat ~ Shannon.s.Diversity, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Amsels.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Age.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ BMI.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Ethnicity.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Marital.Status.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Highest.Education.Level.cat, data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

m <- polr(Nugent.score.cat ~ Current.or.chronic.conditions...y.1..n.0., data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

m <- polr(Nugent.score.cat ~ Genital.Infections..y.1..n.0., data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

m <- polr(Nugent.score.cat ~ BV..number.of.episodes.2.months., data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

m <- polr(Nugent.score.cat ~ BV..number.of.episodes.year., data = total, Hess=TRUE)
summary(m)
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

m <- polr(Nugent.score.cat ~ BV..number.of.episodes.lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Yeast..2months., data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Yeast..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Yeast..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ UTI..2.months., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ UTI..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ UTI..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Trich..2.months., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Trich..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Trich..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genital.Warts..2months., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genital.Warts..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genital.Warts..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genital.Herpes..2months., data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Genital.Herpes..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genital.Herpes..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Chlamydia..2.months., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Chlamydia..year., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Chlamydia..lifetime., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Gonorrhea, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Syphillis, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Antimicrobial.Use..y.1..n.0., data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ X.Non..Prescription..y.1..n.0., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Freq.of.Menstrual.Period.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Tampon.Use.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..g., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..term., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..p., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..sa., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..ta., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Pregnancy.History..l., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Use.of.douche.products..y.1..n.0., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Used.in.the.past.48.hours, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Used.in.past.48.hours, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Sexual.Partners.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Number.partners.in.past.2.months.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Number.partners.in.past.year.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Freq.oral.sex.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Freq.anal.sex.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Freq.sex.toy.use.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ use.of.drugs..y.1..n.0.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ alcohol.use..y.1..n.0.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Actinobacteria.sp., data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Atopobium.vaginae, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Clostridia.sp..BVAB2, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Clostridium.genomosp..BVAB3, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Escherichia.coli, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Gardnerella.vaginalis.Group.A, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Gardnerella.vaginalis.Group.B, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Gardnerella.vaginalis.Group.C, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Gardnerella.vaginalis.Group.D, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Klebsiella.pneumoniae, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Lactobacillus.crispatus, data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Lactobacillus.gasseri, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Lactobacillus.iners, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Lactobacillus.jensenii, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Megasphaera.sp..genomosp..type.1, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Actinobacteria, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Bacteria, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Bacteroidetes, data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Other.Clostridium, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Firmicutes, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Lactobacillus, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Prevotella, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Proteobacteria, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Streptococcus, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Prevotella.amnii, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Prevotella.timonensis, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Streptococcus.devriesei, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Contraception.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Presence.Symptoms.2wks, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Abnormal.discharge.2wks, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Abnormal.odor.2wks, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Irritation.Discomfort.2wks, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Symptoms.2wks, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Presence.Symptoms.48hrs, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Irritation.Discomfort.48hrs, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Other.Symptoms.48hrs, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Preg.livebirth.ever, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Chlamydia.ever, data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ Bac.STI.ever, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Herpes.ever, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Genwarts.ever, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ any.sx.pain, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ sx.pain.50.over, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ sx.pain.100, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contraception.H, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contraception.S.S, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contraception.S.P, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contraception.B.M, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contraception.C.IUD, data = total, Hess=TRUE)
summary(m)
ctable <- coef(summary(m))
pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
m <- polr(Nugent.score.cat ~ HContr.Combination.pill, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ HContr.mirena, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ contr_type, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ condoms.48h, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ probiotics.2.months, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ condoms.48h, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ days.since.LMP, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ weeks.since.LMP, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ weeks.since.LMP.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ CST.cat, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Abnormal.odor.48hrs, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ Abnormal.discharge.48hrs, data = total, Hess=TRUE)
summary(m)
m <- polr(Nugent.score.cat ~ oral.sex.in.past.48.hours..y.1..n.0., data = total, Hess=TRUE)
summary(m)

#CST.cat with all variables
#get to be treated as continuous
total$CST.cat <- as.numeric(total$CST.cat)

mylogit <- glm(formula = CST.cat ~ Shannon.s.Diversity, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Amsels.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Age.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BMI.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Ethnicity.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Marital.Status.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Highest.Education.Level.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Current.or.chronic.conditions...y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Infections..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.2.months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ BV..number.of.episodes.lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..2months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Yeast..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..2.months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ UTI..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..2.months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Trich..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..2months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Warts..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..2months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genital.Herpes..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..2.months., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..year., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia..lifetime., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gonorrhea, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Syphillis, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Antimicrobial.Use..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ X.Non..Prescription..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.of.Menstrual.Period.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Tampon.Use.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..g., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..term., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..p., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..sa., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..ta., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Pregnancy.History..l., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Use.of.douche.products..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Used.in.the.past.48.hours, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Used.in.past.48.hours, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Sexual.Partners.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Number.partners.in.past.2.months.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Number.partners.in.past.year.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.oral.sex.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.anal.sex.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Freq.sex.toy.use.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ use.of.drugs..y.1..n.0.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ alcohol.use..y.1..n.0.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Actinobacteria.sp., data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Atopobium.vaginae, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Clostridia.sp..BVAB2, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Clostridium.genomosp..BVAB3, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Escherichia.coli, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.A, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.B, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.C, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Gardnerella.vaginalis.Group.D, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Klebsiella.pneumoniae, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.crispatus, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.gasseri, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.iners, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Lactobacillus.jensenii, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Megasphaera.sp..genomosp..type.1, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Actinobacteria, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Bacteria, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Bacteroidetes, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Clostridium, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Firmicutes, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Lactobacillus, data=total, family =  poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Prevotella, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Proteobacteria, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Streptococcus, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Prevotella.amnii, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Streptococcus.devriesei, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Contraception.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Presence.Symptoms.2wks, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.discharge.2wks, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.odor.2wks, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Irritation.Discomfort.2wks, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Symptoms.2wks, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Presence.Symptoms.48hrs, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Irritation.Discomfort.48hrs, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Other.Symptoms.48hrs, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Preg.livebirth.ever, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Chlamydia.ever, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Bac.STI.ever, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Herpes.ever, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Genwarts.ever, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ any.sx.pain, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ sx.pain.50.over, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ sx.pain.100, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.H, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.S.S, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.S.P, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.B.M, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contraception.C.IUD, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ HContr.Combination.pill, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ HContr.mirena, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ contr_type, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ condoms.48h, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ probiotics.2.months, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ days.since.LMP, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ weeks.since.LMP, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ weeks.since.LMP.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Nugent.score.cat, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Prevotella.timonensis, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.discharge.48hrs, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ Abnormal.odor.48hrs, data=total, family = poisson(link = "log"))
summary(mylogit)
mylogit <- glm(formula = CST.cat ~ oral.sex.in.past.48.hours..y.1..n.0., data=total, family = poisson(link = "log"))
summary(mylogit)


#Amsels.cat with variables CIs
mylogit <- glm(formula = Amsels.cat ~ Shannon.s.Diversity, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ CST.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Age.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BMI.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Ethnicity.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Marital.Status.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Highest.Education.Level.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Current.or.chronic.conditions...y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Infections..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.2.months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..2months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..2.months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..2.months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..2months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..2months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..2.months., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..year., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..lifetime., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gonorrhea, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Syphillis, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Antimicrobial.Use..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ X.Non..Prescription..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.of.Menstrual.Period.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Tampon.Use.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..g., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..term., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..p., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..sa., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..ta., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..l., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Use.of.douche.products..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Used.in.the.past.48.hours, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Used.in.past.48.hours, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Sexual.Partners.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Number.partners.in.past.2.months.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Number.partners.in.past.year.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.oral.sex.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.anal.sex.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.sex.toy.use.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ use.of.drugs..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ alcohol.use..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Actinobacteria.sp., data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Atopobium.vaginae, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Clostridia.sp..BVAB2, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Clostridium.genomosp..BVAB3, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Escherichia.coli, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.A, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.B, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.C, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.D, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Klebsiella.pneumoniae, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.crispatus, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.gasseri, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.iners, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.jensenii, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Megasphaera.sp..genomosp..type.1, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Actinobacteria, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Bacteria, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Bacteroidetes, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Clostridium, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Firmicutes, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Lactobacillus, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Prevotella, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Proteobacteria, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Streptococcus, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Prevotella.amnii, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Streptococcus.devriesei, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Contraception.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Presence.Symptoms.2wks, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Abnormal.discharge.2wks, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Abnormal.odor.2wks, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Irritation.Discomfort.2wks, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Symptoms.2wks, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Presence.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Irritation.Discomfort.48hrs, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Preg.livebirth.ever, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia.ever, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Bac.STI.ever, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Herpes.ever, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genwarts.ever, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ any.sx.pain, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ sx.pain.50.over, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ sx.pain.100, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.H, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.S.S, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.S.P, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.B.M, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.C.IUD, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ HContr.Combination.pill, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ HContr.mirena, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contr_type, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ condoms.48h, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ probiotics.2.months, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ days.since.LMP, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ weeks.since.LMP, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ weeks.since.LMP.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Nugent.score.cat, data=total, family = binomial(link = "logit"))
confint(mylogit)

#Amsels.cat with variables 
mylogit <- glm(formula = Amsels.cat ~ Shannon.s.Diversity, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ CST.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Age.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BMI.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Ethnicity.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Marital.Status.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Highest.Education.Level.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Current.or.chronic.conditions...y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Infections..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ BV..number.of.episodes.lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Yeast..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ UTI..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Trich..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Warts..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..2months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genital.Herpes..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..2.months., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..year., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia..lifetime., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gonorrhea, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Syphillis, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Antimicrobial.Use..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ X.Non..Prescription..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.of.Menstrual.Period.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Tampon.Use.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..g., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..term., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..p., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..sa., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..ta., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Pregnancy.History..l., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Use.of.douche.products..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Used.in.the.past.48.hours, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Use.of.feminine.wipes.or.genital.deodrant..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Used.in.past.48.hours, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Sexual.Partners.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Number.partners.in.past.2.months.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Number.partners.in.past.year.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Vaginal.intercourse.in.past.48.hours..y.1..n.0., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.oral.sex.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.anal.sex.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Freq.sex.toy.use.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ use.of.drugs..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ alcohol.use..y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ smoker..current.or.in.past...y.1..n.0.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Actinobacteria.sp., data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Atopobium.vaginae, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Clostridia.sp..BVAB2, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Clostridium.genomosp..BVAB3, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Escherichia.coli, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.A, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.B, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.C, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Gardnerella.vaginalis.Group.D, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Klebsiella.pneumoniae, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.crispatus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.gasseri, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.iners, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Lactobacillus.jensenii, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Megasphaera.sp..genomosp..type.1, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Actinobacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Bacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Bacteroidetes, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Clostridium, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Firmicutes, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Lactobacillus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Prevotella, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Proteobacteria, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Streptococcus, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Prevotella.amnii, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Streptococcus.devriesei, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ How.often.pain.experienced.during.vaginal.intercourse.percentage, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Contraception.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Presence.Symptoms.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Abnormal.discharge.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Abnormal.odor.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Irritation.Discomfort.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Symptoms.2wks, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Presence.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Irritation.Discomfort.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Other.Symptoms.48hrs, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Preg.livebirth.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Chlamydia.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Bac.STI.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Herpes.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Genwarts.ever, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ any.sx.pain, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ sx.pain.50.over, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ sx.pain.100, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.H, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.S.S, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.S.P, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.B.M, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contraception.C.IUD, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ HContr.Combination.pill, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ HContr.mirena, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ contr_type, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ condoms.48h, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ probiotics.2.months, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ days.since.LMP, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ weeks.since.LMP, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ weeks.since.LMP.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)
mylogit <- glm(formula = Amsels.cat ~ Nugent.score.cat, data=total, family = binomial(link = "logit"))
summary(mylogit)